version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
environment:
  VisualStudioVersion: 14.0
  GeneratePInvokesTxt: true
  NuGetApiKey:
    secure: Ql19CstT9GvFNeSIAjXvgHXZg+/pNaYJ2jVkzde4LT2vwSyjiQgQ+M332wVYtu+r
cache:
- '%USERPROFILE%\.nuget\packages'
before_build:
- ps: nuget restore src -Verbosity quiet
build:
  project: src\pinvoke.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
- path: bin\**\*.pinvokes.txt
  name: PInvoke method coverage
- path: bin\**\*.exports.txt
  name: Exported methods
on_success:
- ps: >-
    if ($env:NuGetApiKey -and $env:APPVEYOR_REPO_TAG_NAME -match "^v\d\.\d") {
        Write-Output "Publishing release packages to nuget.org due to pushed tag $env:APPVEYOR_REPO_TAG_NAME"
        Get-ChildItem bin\Release\Packages\*.nupkg -exclude *.symbols.nupkg |% {
            nuget push $_ -ApiKey $env:NuGetApiKey
        }
    }
deploy:
- provider: NuGet
  server: https://www.myget.org/F/aarnott-appveyortest/api/v3/index.json
  api_key:
    secure: 1sykv5RS3PAzoptuMBOF/WYkvdEzlHwIv3hBMkkWGJHsoy6JnXdiNq8ShOtSgvzD
- provider: Environment
  name: EnvAnotifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c4d61fc5002e9a62a22f
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
